# Generated by Django 5.0.4 on 2024-04-11 13:45
from django.contrib.auth.models import User
from django.db import migrations


def create_superuser(apps, schema_editor):
    User.objects.create_superuser('admin', 'admin@example.com', 'admin')


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
